[package]
name = "utility_ai"
version = "0.1.0"
authors = ["Derek Stobbe <djstobbe@gmail.com>"]
edition = "2018"

[dependencies]
utils = { path = "../utils/" }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
log = "0.4.8"
pretty_env_logger = "0.4.0"
