[package]
name = "ai"
version = "0.1.0"
edition = "2018"

[dependencies]
legion = { git = "https://github.com/TomGillen/legion" }
log = "0.4.8"

components = { path = "../components"}
vaultkeeper_shared = { path = "../../vaultkeeper_shared" }
