[package]
name = "utils"
version = "0.1.0"
edition = "2018"

[dependencies]
bracket-lib = { version = "0.7.0", features = ["serde"] }
log = "0.4.8"
serde = { version = "1.0.104", features = ["derive"] }
